# Generated by Django 5.2.18 on 2026-10-07 09:08

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='numer mieszkania')),
                ('title', models.CharField(max_length=120, verbose_name='nazwa')),
                ('area', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='powierzchnia (m²)')),
                ('rooms', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='liczba pokoi')),
                ('floor', models.PositiveSmallIntegerField(default=0, verbose_name='piętro')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='cena (zł)')),
                ('description', models.TextField(verbose_name='opis')),
                ('status', models.CharField(choices=[('available', 'Dostępne'), ('reserved', 'Zarezerwowane'), ('sold', 'Sprzedane')], default='available', max_length=10, verbose_name='status')),
            ],
            options={
                'verbose_name': 'mieszkanie',
                'verbose_name_plural': 'mieszkania',
                'ordering': ['number'],
            },
        ),
    ]
